name: BuildableFactions
version: '${project.version}'
main: mine.plugins.lunar.buildablefactions.Main
load: POSTWORLD
author: PingoLunar
libraries:
  - io.github.skytasul:glowingentities:1.3
api-version: 1.20
depend:
  - Vault
permissions:
  bf.*:
    default: op
    children:
      bf.debug: true
      bf.config: true